default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hello_rails_development
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  <<: *default
  database: hello_rails_test
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>

production:
  <<: *default
  database: hello_rails_production
