Greeting.create(message: 'Good morning')
Greeting.create(message: 'Good evening')
Greeting.create(message: 'Good afternoon')
Greeting.create(message: 'Hello world!')
Greeting.create(message: 'Nice to meet you!')
